#!/usr/bin/env python
"""Frozen-checkpoint spatial-spectrum covariance probe for field Dual-Wiener.

For each rollout horizon and channel, centered residuals are whitened by their
per-coordinate standard deviation.  The estimator then averages their 2-D
power spectra across balanced physical trajectories.  A noise covector is
generated by filtering real white noise with the square root of that spectrum,
which preserves stationary spatial second-order structure while randomizing
phase and absolute feature location.  Multiplying by the original coordinate
standard deviations restores the diagonal heteroscedasticity exactly in
expectation.

This is a frozen-checkpoint estimator diagnostic.  It compares the existing
diagonal Gaussian with a spatially colored Gaussian on the same fully-open
route graph; it does not equate all residual covariance with irreducible noise.
"""
from __future__ import annotations

import argparse
import itertools
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from internal_dw.datasets.registry import build_dataloaders
from internal_dw.models.dual_wiener import solve_box_wiener_2x2
from internal_dw.models.registry import build_model
from internal_dw.utils import load_checkpoint, unwrap_model
from probe_gradient_dynamics import _infer_thewell_shape, _namespace
from probe_thewell_lowrank_wiener import (
    _add_moment,
    _configure_open_route_graph,
    _means,
    _reset_graph_state,
    _restore_route_graph,
    _rollout,
)
from probe_wiener_oracle import RouteCapture, covector_loss, push
from select_thewell_crossfit_pca_rank import (
    _sample_unique_physical_trajectories,
    _stratified_fold_indices,
)


VARIANTS = ("diagonal", "spatial_spectrum")


def _rfft_frequency_weights(width: int, reference: torch.Tensor) -> torch.Tensor:
    frequency_width = width // 2 + 1
    weights = reference.new_full((frequency_width,), 2.0)
    weights[0] = 1.0
    if width % 2 == 0:
        weights[-1] = 1.0
    return weights


def _normalize_spectrum(power: torch.Tensor, width: int) -> torch.Tensor:
    """Normalize [K,C,H,W//2+1] rFFT power to unit spatial variance."""
    weights = _rfft_frequency_weights(width, power)
    variance = (
        power * weights.view(1, 1, 1, -1)
    ).sum(dim=(-2, -1), keepdim=True) / float(power.shape[-2] * width)
    normalized = power / variance.clamp_min(1e-20)
    return normalized.clamp_min(0.0)


def _fit_spectral_covariance(residuals: torch.Tensor, variance_floor: float = 1e-8):
    if residuals.ndim != 5 or residuals.shape[0] < 2:
        raise ValueError("spectral covariance expects residuals [N,K,C,H,W], N>=2")
    residuals = residuals.float()
    centered = residuals - residuals.mean(dim=0, keepdim=True)
    variance = centered.square().mean(dim=0)
    floor = variance.mean().clamp_min(1e-30) * float(variance_floor)
    sigma = torch.sqrt(variance + floor)
    whitened = centered / sigma.unsqueeze(0)
    transform = torch.fft.rfft2(whitened, dim=(-2, -1), norm="ortho")
    power = transform.abs().square().mean(dim=0)
    power = _normalize_spectrum(power, int(residuals.shape[-1]))
    return {
        "sigma": sigma.contiguous(),
        "power": power.contiguous(),
        "filter": power.sqrt().contiguous(),
    }


def _spectrum_stability(full, split_models):
    # Compare only the departure from white power.  Raw positive spectra can
    # have a deceptively high cosine even when their colored components differ.
    full_color = (full["power"] - 1.0).reshape(-1).double()
    vectors = [(model["power"] - 1.0).reshape(-1).double() for model in split_models]
    raw_vectors = [model["power"].reshape(-1).double() for model in split_models]

    def pairwise_cosines(items):
        values = []
        for left, right in itertools.combinations(items, 2):
            denominator = float(left.norm() * right.norm())
            values.append(float(torch.dot(left, right) / max(denominator, 1e-30)))
        return values

    color_cosines = pairwise_cosines(vectors)
    raw_cosines = pairwise_cosines(raw_vectors)
    mean_vector = torch.stack(vectors).mean(dim=0)
    denominator = max(float(mean_vector.norm()), 1e-30)
    deviations = [float((vector - mean_vector).norm()) / denominator for vector in vectors]
    return {
        "color_rms_from_white": float(full_color.square().mean().sqrt()),
        "split_color_cosine_mean": float(np.mean(color_cosines)),
        "split_color_cosine_min": float(np.min(color_cosines)),
        "split_raw_spectrum_cosine_mean": float(np.mean(raw_cosines)),
        "split_relative_color_deviation_mean": float(np.mean(deviations)),
        "split_relative_color_deviation_max": float(np.max(deviations)),
    }


def _noise_sample(model, variant: str, epsilon: torch.Tensor) -> torch.Tensor:
    if variant == "diagonal":
        standardized = epsilon
    elif variant == "spatial_spectrum":
        white_spectrum = torch.fft.rfft2(epsilon, dim=(-2, -1), norm="ortho")
        standardized = torch.fft.irfft2(
            white_spectrum * model["filter"],
            s=epsilon.shape[-2:],
            dim=(-2, -1),
            norm="ortho",
        )
    else:
        raise ValueError(f"unknown spectral variant {variant!r}")
    return standardized * model["sigma"]


def _summarize_routes(total, noises, depth: int, checkpoint_gains):
    common = set(total)
    for variant in VARIANTS:
        common &= set(noises[variant])
    routes = sorted(common)
    if not routes:
        raise RuntimeError("no common route VJPs were captured")
    summaries, rows = {}, []
    for variant in VARIANTS:
        alpha, branch, fractions = [], [], []
        for route in routes:
            T, R = total[route], noises[variant][route]
            gain = solve_box_wiener_2x2(T, R).cpu().double()
            fraction = float(torch.trace(R) / torch.trace(T).clamp_min(1e-30))
            horizon, layer = divmod(int(route), int(depth))
            rows.append(
                {
                    "variant": variant,
                    "route_index": int(route),
                    "horizon_index": int(horizon),
                    "layer_index": int(layer),
                    "alpha": float(gain[0]),
                    "m": float(gain[1]),
                    "noise_fraction": fraction,
                    "total_moment": T.tolist(),
                    "noise_moment": R.tolist(),
                }
            )
            alpha.append(float(gain[0]))
            branch.append(float(gain[1]))
            fractions.append(fraction)
        summaries[variant] = {
            "routes": len(routes),
            "alpha_mean": float(np.mean(alpha)),
            "alpha_sd": float(np.std(alpha)),
            "alpha_median": float(np.median(alpha)),
            "m_mean": float(np.mean(branch)),
            "m_sd": float(np.std(branch)),
            "m_median": float(np.median(branch)),
            "noise_fraction_mean": float(np.mean(fractions)),
            "noise_fraction_median": float(np.median(fractions)),
        }
    values = []
    for route in routes:
        horizon, layer = divmod(route, int(depth))
        if horizon < checkpoint_gains.shape[0] and layer < checkpoint_gains.shape[1]:
            values.append(checkpoint_gains[horizon, layer])
    checkpoint = None
    if values:
        values = np.asarray(values)
        checkpoint = {
            "routes": int(values.shape[0]),
            "alpha_mean": float(values[:, 0].mean()),
            "m_mean": float(values[:, 1].mean()),
        }
    return summaries, rows, checkpoint


def _plot(out: Path, summaries, checkpoint, stability):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    x = np.arange(2)
    alpha = [summaries[name]["alpha_mean"] for name in VARIANTS]
    branch = [summaries[name]["m_mean"] for name in VARIANTS]
    fraction = [summaries[name]["noise_fraction_mean"] for name in VARIANTS]
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.7))
    axes[0].plot(x, alpha, "o-", label=r"$\alpha$")
    axes[0].plot(x, branch, "s-", label=r"$m$")
    if checkpoint:
        axes[0].axhline(checkpoint["alpha_mean"], color="C0", ls=":", lw=1)
        axes[0].axhline(checkpoint["m_mean"], color="C1", ls=":", lw=1)
    axes[0].set_ylim(-0.03, 1.03)
    axes[0].set_ylabel("mean route gain")
    axes[0].legend(frameon=False)
    axes[1].plot(x, fraction, "o-", color="C3")
    axes[1].axhline(1.0, color="0.4", ls="--", lw=1)
    axes[1].set_ylabel(r"mean $\mathrm{tr}(R)/\mathrm{tr}(T)$")
    labels = ["diagonal", "spatial spectrum"]
    for axis in axes:
        axis.set_xticks(x, labels)
        axis.grid(alpha=0.2)
    fig.suptitle(
        f"split colored-spectrum cosine = {stability['split_color_cosine_mean']:.3f}",
        fontsize=9,
    )
    fig.tight_layout()
    fig.savefig(out.with_suffix(".png"), dpi=180)
    fig.savefig(out.with_suffix(".pdf"))
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt", required=True)
    parser.add_argument("--K", type=int, default=32)
    parser.add_argument("--fit_trajectories", type=int, default=48)
    parser.add_argument("--probe_trajectories", type=int, default=9)
    parser.add_argument("--noise_draws", type=int, default=2)
    parser.add_argument("--stability_splits", type=int, default=4)
    parser.add_argument("--variance_floor", type=float, default=1e-8)
    parser.add_argument("--gpu", type=int, default=0)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", required=True)
    cli = parser.parse_args()

    torch.manual_seed(int(cli.seed))
    np.random.seed(int(cli.seed))
    checkpoint = torch.load(cli.ckpt, map_location="cpu", weights_only=False)
    args = _namespace(checkpoint["args"])
    args.num_workers = 0
    args.local_batch_size = 1
    train_loader, val_loader, _ = build_dataloaders(args, rank=0, world_size=1)
    _infer_thewell_shape(args, train_loader)
    if str(getattr(args, "model_name", "")) != "unet_field":
        raise ValueError("spectral covariance probe currently supports The-Well unet_field")
    device = torch.device(f"cuda:{int(cli.gpu)}" if torch.cuda.is_available() else "cpu")
    model = build_model(args, rank=0)
    load_checkpoint(model, cli.ckpt, map_location=str(device), strict=True)
    raw = unwrap_model(model).to(device).eval()
    for parameter in raw.parameters():
        parameter.requires_grad_(False)
    dw = getattr(raw, "dual_wiener", None)
    if dw is None:
        raise RuntimeError("checkpoint/model has no Dual-Wiener controller")
    K = min(int(cli.K), int(dw.max_horizon))

    fit_pool = _sample_unique_physical_trajectories(
        train_loader.dataset, args, K, cli.fit_trajectories, cli.seed + 607
    )
    probe_pool = _sample_unique_physical_trajectories(
        val_loader.dataset, args, K, cli.probe_trajectories, cli.seed + 701
    )
    if len(fit_pool) < 2 or not probe_pool:
        raise RuntimeError(
            f"insufficient unique trajectories: fit={len(fit_pool)} probe={len(probe_pool)}"
        )
    print(
        f"[setup] checkpoint_epoch={checkpoint.get('epoch')} K={K} "
        f"fit_trajectories={len(fit_pool)} probe_trajectories={len(probe_pool)} "
        f"noise_draws={cli.noise_draws} device={device}",
        flush=True,
    )

    residual_batches = []
    for index, item in enumerate(fit_pool):
        predictions, targets = _rollout(raw, item, args, K, device, graph=False)
        residual_batches.append(torch.stack(
            [(prediction - target)[0, 0] for prediction, target in zip(predictions, targets)]
        ).cpu())
        print(f"[residual library] {index + 1}/{len(fit_pool)}", flush=True)
    residuals = torch.stack(residual_batches).to(device)
    spectral_model = _fit_spectral_covariance(residuals, cli.variance_floor)
    split_indices = _stratified_fold_indices(
        fit_pool, int(cli.stability_splits), cli.seed + 809
    )
    split_models = [
        _fit_spectral_covariance(
            residuals[torch.as_tensor(indices, device=device)], cli.variance_floor
        )
        for indices in split_indices
    ]
    stability = _spectrum_stability(spectral_model, split_models)
    print(
        "[spectrum stability] "
        f"color_rms={stability['color_rms_from_white']:.5f} "
        f"color_cos={stability['split_color_cosine_mean']:.4f} "
        f"color_cos_min={stability['split_color_cosine_min']:.4f} "
        f"relative_dev={stability['split_relative_color_deviation_mean']:.4f}",
        flush=True,
    )

    total_store: dict[int, list[Any]] = {}
    noise_stores = {variant: {} for variant in VARIANTS}
    checkpoint_gains = dw.coefficients[:K].detach().cpu().numpy()
    dw, saved = _configure_open_route_graph(raw)
    capture = RouteCapture(dw)
    try:
        for start_index, item in enumerate(probe_pool):
            _reset_graph_state(dw)
            predictions, targets = _rollout(raw, item, args, K, device, graph=True)
            roots = list(dw._root_refs)
            if not roots:
                raise RuntimeError("fully-open graph exposed no autograd root")
            actual = [(prediction - target).detach() for prediction, target in zip(predictions, targets)]
            pairs = push(covector_loss(predictions, actual), roots, capture, retain=True)
            for route, pair in pairs.items():
                _add_moment(total_store, route, pair)

            generator = torch.Generator(device=device).manual_seed(
                int(cli.seed) * 100003 + start_index * 1013 + 907
            )
            K_, C, H, W = spectral_model["sigma"].shape
            for draw in range(int(cli.noise_draws)):
                epsilon = torch.randn((K_, C, H, W), device=device, generator=generator)
                for variant_index, variant in enumerate(VARIANTS):
                    sample = _noise_sample(spectral_model, variant, epsilon)
                    vecs = [sample[h : h + 1].unsqueeze(0) for h in range(K)]
                    last = (
                        start_index == len(probe_pool) - 1
                        and draw == int(cli.noise_draws) - 1
                        and variant_index == len(VARIANTS) - 1
                    )
                    route_pairs = push(
                        covector_loss(predictions, vecs), roots, capture, retain=not last
                    )
                    for route, pair in route_pairs.items():
                        _add_moment(noise_stores[variant], route, pair)
            print(
                f"[route probe] {start_index + 1}/{len(probe_pool)} "
                f"captured_routes={len(pairs)}",
                flush=True,
            )
            del predictions, targets, roots, actual
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
    finally:
        capture.close()
        _restore_route_graph(raw, dw, saved)

    total = _means(total_store)
    noises = {variant: _means(store) for variant, store in noise_stores.items()}
    summaries, route_rows, checkpoint_summary = _summarize_routes(
        total, noises, int(dw.depth), checkpoint_gains
    )
    output = {
        "format_version": 1,
        "probe": "frozen_checkpoint_random_phase_spatial_spectrum_wiener",
        "checkpoint": str(cli.ckpt),
        "checkpoint_epoch": checkpoint.get("epoch"),
        "dataset": str(getattr(args, "dataset", "")),
        "thewell_dataset_name": str(getattr(args, "thewell_dataset_name", "")),
        "K": K,
        "fit_split": "train",
        "gain_probe_split": "validation",
        "fit_unique_trajectories": len(fit_pool),
        "probe_unique_trajectories": len(probe_pool),
        "noise_draws_per_probe": int(cli.noise_draws),
        "variance_floor_fraction": float(cli.variance_floor),
        "spectrum_stability": stability,
        "variant_summary": summaries,
        "checkpoint_gain_summary": checkpoint_summary,
        "route_rows": route_rows,
        "scope": (
            "Estimator diagnostic under a per-horizon/channel stationary spatial "
            "Gaussian residual model; residual covariance is not identified with "
            "irreducible noise."
        ),
    }
    out = Path(cli.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.with_suffix(".json").write_text(json.dumps(output, indent=2), encoding="utf-8")
    np.savez_compressed(
        out.with_suffix(".npz"),
        normalized_power=spectral_model["power"].detach().cpu().numpy(),
    )
    _plot(out, summaries, checkpoint_summary, stability)

    print("\n=== random-phase spatial-spectrum route gains ===", flush=True)
    print(" estimator              alpha        m   noise_frac", flush=True)
    for variant in VARIANTS:
        row = summaries[variant]
        print(
            f"{variant:22s} {row['alpha_mean']:8.4f}  {row['m_mean']:8.4f}  "
            f"{row['noise_fraction_mean']:10.4f}",
            flush=True,
        )
    if checkpoint_summary:
        print(
            f"{'checkpoint':22s} {checkpoint_summary['alpha_mean']:8.4f}  "
            f"{checkpoint_summary['m_mean']:8.4f}",
            flush=True,
        )
    print(f"[out] {out.with_suffix('.json')}", flush=True)
    print(f"[out] {out.with_suffix('.png')}", flush=True)


if __name__ == "__main__":
    main()
