#!/usr/bin/env bash
# Canonical single-seed configuration for the known-SNR five-panel closure.

KNOWN_SNR_SEED=0
KNOWN_SNR_TRAIN_HORIZON=32
KNOWN_SNR_EXACT_LOCAL_BATCH=4
KNOWN_SNR_EXACT_GRAD_ACCUM_STEPS=8
KNOWN_SNR_ROUTING_LOCAL_BATCH=4
KNOWN_SNR_EFFECTIVE_BATCH=32
KNOWN_SNR_CANONICAL_ROUTING_WORLD_SIZE=4
KNOWN_SNR_EPOCHS=100
KNOWN_SNR_EARLY_STOP_PATIENCE=20
KNOWN_SNR_LEARNING_RATE=1e-4
KNOWN_SNR_WEIGHT_DECAY=1e-4
KNOWN_SNR_GRAD_CLIP=1.0
# Full-BPTT reference checkpoint; routed-arm workers remain configured separately.
KNOWN_SNR_NUM_WORKERS=4
KNOWN_SNR_PANEL_REPETITIONS=4
KNOWN_SNR_PROBE_STARTS=8
KNOWN_SNR_FUTURE_NOISE_DRAWS=64
