"""Global-horizon Wiener weighting for autoregressive rollout losses.

The internal Dual-Wiener controller solves many local route problems.  This
controller instead treats the complete parameter gradients of the K horizon
losses as one vector-valued observation.  On a calibration batch it estimates

    T_ij = <grad l_i, grad l_j>,
    R_ij = <grad n_i, grad n_j>,

where ``n_i`` is an antithetic score perturbation generated by the same
domain-specific innovation sampler used by Dual-Wiener.  The horizon gradient
    features are averaged over the complete shared-start DDP batch before either
    Gram is formed, and ``R`` averages independent innovation-draw Grams.  An
    optional ``superbatch_groups=M`` calibration partitions that same logical
    batch into M equal, disjoint subgroups, forms one batch-mean gradient per
    subgroup, and averages their Grams.  The real optimizer backward continues
    to use the complete-batch loss; the grouped moment is therefore an explicit
    variance-reduction engineering geometry, not the exact complete-batch
    update Gram.  With ``P = PSD(T - R)``, the box-constrained Wiener problem is

    min_{0 <= w <= 1} 0.5 w^T T w - w^T P 1.

Optionally, ``local_fidelity`` shrinks this aggregate-gradient objective
towards the sum of the K separate per-horizon Wiener risks.  For
``eta = local_fidelity`` the solved objective is

    ((1-eta)/K) E ||sum_k (w_k g_k - s_k)||^2
        + eta sum_k E ||w_k g_k - s_k||^2.

Thus ``eta=0`` is the original joint solve and ``eta=1`` keeps only the
diagonal, per-horizon Wiener problems.  Intermediate values penalize fragile
cross-horizon error cancellation while retaining a single, model-independent
coefficient per relative rollout horizon.

Only the backward derivative of each horizon loss is multiplied by ``w_i``;
its forward value is unchanged.  Consequently checkpoint selection and logged
losses remain directly comparable with Exact BPTT.
"""

from __future__ import annotations

from collections import defaultdict
from typing import DefaultDict, Dict, Iterable, List, Optional, Sequence, Tuple

import torch
import torch.distributed as dist
from torch import nn

from .dual_wiener import DualWienerController


def solve_box_wiener(
    total: torch.Tensor,
    signal: torch.Tensor,
    *,
    initial: Optional[torch.Tensor] = None,
    ridge: float = 1e-8,
    anchor: float = 0.0,
    iterations: int = 256,
) -> Tuple[torch.Tensor, float]:
    """Solve the convex global-horizon Wiener problem by projected FISTA.

    ``ridge`` is a dimensionless numerical ridge relative to the mean diagonal
    of ``total``.  ``anchor`` is a separate statistical regularizer with the
    same normalization and adds ``0.5 * anchor * ||w - 1||^2``.  Thus uncertain
    directions fall back to the fully-open backward operator (TBPTT in the
    hybrid setting), rather than to a zero update.  The return value is
    ``(weights, projected_gradient_inf_norm)``.
    """

    if total.ndim != 2 or total.shape[0] != total.shape[1]:
        raise ValueError(f"total must be square, got {tuple(total.shape)}")
    if signal.shape != total.shape:
        raise ValueError(
            f"signal shape {tuple(signal.shape)} does not match {tuple(total.shape)}"
        )
    dimension = int(total.shape[0])
    if dimension == 0:
        return total.new_empty(0), 0.0

    work_dtype = torch.float64
    device = total.device
    total64 = 0.5 * (total.to(work_dtype) + total.to(work_dtype).T)
    signal64 = 0.5 * (signal.to(work_dtype) + signal.to(work_dtype).T)
    scale = total64.diagonal().mean().abs().clamp_min(1e-30)
    ridge_abs = max(float(ridge), 0.0) * scale
    anchor_abs = max(float(anchor), 0.0) * scale
    eye = torch.eye(dimension, device=device, dtype=work_dtype)
    ones = torch.ones(dimension, device=device, dtype=work_dtype)
    quadratic = total64 + (ridge_abs + anchor_abs) * eye
    linear = signal64 @ ones + anchor_abs * ones

    # A safe global step for the PSD quadratic.  The numerical ridge makes the
    # map well defined even during the first low-rank calibration batches.
    lipschitz = torch.linalg.eigvalsh(quadratic).amax().clamp_min(1e-30)
    if initial is None:
        current = torch.ones(dimension, device=device, dtype=work_dtype)
    else:
        current = initial.to(device=device, dtype=work_dtype).clamp(0.0, 1.0)
    extrapolated = current.clone()
    momentum = current.new_tensor(1.0)
    for _ in range(max(1, int(iterations))):
        gradient = quadratic @ extrapolated - linear
        next_value = (extrapolated - gradient / lipschitz).clamp(0.0, 1.0)
        next_momentum = 0.5 * (1.0 + torch.sqrt(1.0 + 4.0 * momentum.square()))
        extrapolated = next_value + ((momentum - 1.0) / next_momentum) * (
            next_value - current
        )
        current = next_value
        momentum = next_momentum

    gradient = quadratic @ current - linear
    projected = current - (current - gradient).clamp(0.0, 1.0)
    residual = float(projected.abs().amax().detach().cpu())
    return current.to(dtype=total.dtype), residual


def mix_global_local_wiener_moments(
    total: torch.Tensor,
    signal: torch.Tensor,
    local_fidelity: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Return moments for the aggregate/local-fidelity Wiener objective.

    Let ``e_k = w_k g_k - s_k``.  The original global controller minimizes
    ``E||sum_k e_k||^2`` whereas independent scalar Wiener gains minimize
    ``sum_k E||e_k||^2``.  This helper constructs the quadratic and signal
    moments for

        (1-eta)/K * E||sum_k e_k||^2
            + eta * sum_k E||e_k||^2.

    The ``1/K`` makes the common horizon mode and the K-1 contrast modes use
    the same projection normalization.  It has no effect at ``eta=0`` because
    both the quadratic and linear terms receive the same scale.
    """

    if total.ndim != 2 or total.shape[0] != total.shape[1]:
        raise ValueError(f"total must be square, got {tuple(total.shape)}")
    if signal.shape != total.shape:
        raise ValueError(
            f"signal shape {tuple(signal.shape)} does not match {tuple(total.shape)}"
        )
    eta = float(local_fidelity)
    if not 0.0 <= eta <= 1.0:
        raise ValueError("global Wiener local fidelity must lie in [0,1]")
    dimension = int(total.shape[0])
    if dimension == 0:
        return total, signal

    global_scale = (1.0 - eta) / float(dimension)
    total_diagonal = torch.diag_embed(total.diagonal())
    signal_diagonal = torch.diag_embed(signal.diagonal())
    mixed_total = global_scale * total + eta * total_diagonal
    mixed_signal = global_scale * signal + eta * signal_diagonal
    return (
        0.5 * (mixed_total + mixed_total.T),
        0.5 * (mixed_signal + mixed_signal.T),
    )


def _stable_symmetric_eigh(
    matrix: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Eigendecompose a small symmetric moment matrix robustly.

    Horizon Gram matrices can be extremely low rank: dozens of horizon
    coefficients may span only a few effective parameter-gradient directions.
    CUDA's symmetric eigensolver occasionally fails on those nearly repeated
    eigenvalues.  These matrices are at most ``K x K`` (typically 32--64), so a
    CPU float64 solve is negligible beside the VJPs used to construct them and
    is substantially more reliable.  Increasing diagonal jitter is used only
    to obtain the eigensystem; it is subtracted back from the eigenvalues.
    """

    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError(f"matrix must be square, got {tuple(matrix.shape)}")
    device = matrix.device
    symmetric = 0.5 * (matrix.detach().double() + matrix.detach().double().T)
    work = symmetric.cpu()
    if not bool(torch.isfinite(work).all()):
        raise ValueError("moment matrix contains non-finite values")
    if work.numel() == 0:
        return (
            work.new_empty((0,)).to(device=device),
            work.new_empty((0, 0)).to(device=device),
        )

    scale = max(
        float(work.abs().amax()),
        float(work.diagonal().abs().mean()),
        1.0e-30,
    )
    identity = torch.eye(work.shape[0], dtype=work.dtype, device=work.device)
    last_error: Optional[RuntimeError] = None
    for relative_jitter in (0.0, 1.0e-14, 1.0e-12, 1.0e-10, 1.0e-8, 1.0e-6):
        jitter = relative_jitter * scale
        try:
            values, vectors = torch.linalg.eigh(work + jitter * identity)
            values = values - jitter
            return values.to(device=device), vectors.to(device=device)
        except RuntimeError as error:
            last_error = error
    raise RuntimeError("stable symmetric eigendecomposition failed") from last_error


def _psd_projection(matrix: torch.Tensor) -> torch.Tensor:
    matrix64 = 0.5 * (matrix.double() + matrix.double().T)
    values, vectors = _stable_symmetric_eigh(matrix64)
    projected = (vectors * values.clamp_min(0.0).unsqueeze(0)) @ vectors.T
    return projected.to(device=matrix.device, dtype=matrix.dtype)


def project_noise_below_total(
    total: torch.Tensor,
    noise: torch.Tensor,
    *,
    floor: float = 1e-8,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, float]:
    """Project moments onto ``0 <= R <= T`` in the Loewner order.

    Projecting ``T - R`` alone hides whether a finite-sample noise estimate is
    larger than the total moment in some direction.  Whitening by ``T`` and
    clipping the generalized noise eigenvalues to ``[0, 1]`` enforces both
    physical constraints simultaneously.  The returned scalar is the largest
    pre-projection violation outside that interval.
    """

    if total.ndim != 2 or total.shape[0] != total.shape[1]:
        raise ValueError(f"total must be square, got {tuple(total.shape)}")
    if noise.shape != total.shape:
        raise ValueError(
            f"noise shape {tuple(noise.shape)} does not match {tuple(total.shape)}"
        )
    if total.numel() == 0:
        return total, noise, total, 0.0

    dtype = total.dtype
    device = total.device
    total64 = _psd_projection(total).double()
    noise64 = _psd_projection(noise).double()
    scale = total64.diagonal().mean().abs().clamp_min(1e-30)
    eigen_floor = max(float(floor), 0.0) * scale
    values, vectors = _stable_symmetric_eigh(total64)
    values = values.clamp_min(eigen_floor.clamp_min(1e-30))
    root = (vectors * values.sqrt().unsqueeze(0)) @ vectors.T
    inverse_root = (vectors * values.rsqrt().unsqueeze(0)) @ vectors.T
    whitened = inverse_root @ noise64 @ inverse_root
    whitened = 0.5 * (whitened + whitened.T)
    ratios, ratio_vectors = _stable_symmetric_eigh(whitened)
    violation = torch.maximum((-ratios).clamp_min(0.0), (ratios - 1.0).clamp_min(0.0))
    clipped = ratios.clamp(0.0, 1.0)
    whitened_projected = (ratio_vectors * clipped.unsqueeze(0)) @ ratio_vectors.T
    total_projected = 0.5 * (root @ root.T + (root @ root.T).T)
    noise_projected = root @ whitened_projected @ root.T
    noise_projected = 0.5 * (noise_projected + noise_projected.T)
    signal_projected = total_projected - noise_projected
    signal_projected = 0.5 * (signal_projected + signal_projected.T)
    return (
        total_projected.to(device=device, dtype=dtype),
        noise_projected.to(device=device, dtype=dtype),
        signal_projected.to(device=device, dtype=dtype),
        float(violation.amax().detach().cpu()),
    )


def _parameter_gradient_feature(
    objective: torch.Tensor,
    parameters: Sequence[torch.Tensor],
    *,
    sketch_dim: int = 0,
    sketch_seed: int = 0,
) -> Tuple[torch.Tensor, int]:
    """Return an exact or CountSketched complete parameter gradient.

    A positive ``sketch_dim`` bounds memory independently of model size.  The
    same hash is used for every horizon within one calibration, so feature
    inner products estimate the complete parameter-gradient Gram.  Hashes are
    changed across probe batches and averaged by the controller, making the
    collision error zero mean rather than a persistent per-coordinate bias.
    """

    gradients = torch.autograd.grad(
        objective,
        parameters,
        retain_graph=True,
        create_graph=False,
        allow_unused=True,
    )
    total_coordinates = sum(int(parameter.numel()) for parameter in parameters)
    if int(sketch_dim) <= 0:
        pieces = []
        for parameter, gradient in zip(parameters, gradients):
            if gradient is None:
                pieces.append(
                    torch.zeros_like(
                        parameter, memory_format=torch.preserve_format
                    ).reshape(-1)
                )
            else:
                pieces.append(gradient.detach().reshape(-1))
        if not pieces:
            return objective.new_empty(0), 0
        return torch.cat(pieces).float(), total_coordinates

    dimension = int(sketch_dim)
    # Power-of-two buckets make the hash cheap on GPU.  Rounding upward is
    # reported in the exported controller metadata.
    dimension = 1 << max(0, dimension - 1).bit_length()
    feature = torch.zeros(dimension, device=objective.device, dtype=torch.float32)
    coordinate_offset = 0
    chunk_size = 1 << 20
    bucket_offset = int(sketch_seed) * 104729 + 12345
    sign_offset = int(sketch_seed) * 130363 + 67891
    for parameter, gradient in zip(parameters, gradients):
        count = int(parameter.numel())
        if gradient is not None:
            flat = gradient.detach().reshape(-1).float()
            for start in range(0, count, chunk_size):
                stop = min(start + chunk_size, count)
                coordinates = torch.arange(
                    coordinate_offset + start,
                    coordinate_offset + stop,
                    device=flat.device,
                    dtype=torch.int64,
                )
                buckets = (
                    coordinates * 48271 + bucket_offset
                ).bitwise_and(dimension - 1)
                signs = (
                    ((coordinates * 69621 + sign_offset) // dimension)
                    .bitwise_and(1)
                    .to(torch.float32)
                    .mul_(2.0)
                    .sub_(1.0)
                )
                feature.scatter_add_(0, buckets, flat[start:stop] * signs)
        coordinate_offset += count
    return feature, total_coordinates


def parameter_gradient_features(
    objectives: Sequence[torch.Tensor],
    parameters: Sequence[torch.Tensor],
    *,
    sketch_dim: int = 0,
    sketch_seed: int = 0,
) -> Tuple[torch.Tensor, int]:
    """Return one complete-parameter-gradient feature row per objective.

    Keeping features until after distributed reduction is essential.  DDP
    applies the mean parameter gradient, so its Gram is formed from the mean of
    rank-local features, not from the mean of rank-local Grams.
    """

    if not objectives:
        raise ValueError("at least one objective is required")
    rows = []
    normalizer = None
    for objective in objectives:
        row, coordinates = _parameter_gradient_feature(
            objective,
            parameters,
            sketch_dim=int(sketch_dim),
            sketch_seed=int(sketch_seed),
        )
        rows.append(row)
        if normalizer is None:
            normalizer = coordinates
        elif coordinates != normalizer:
            raise RuntimeError("parameter count changed within one Wiener probe")
    return torch.stack(rows), int(normalizer or 0)


def gram_from_gradient_features(
    features: torch.Tensor, parameter_count: int
) -> torch.Tensor:
    """Form a normalized horizon Gram from already-aggregated features."""

    if features.ndim != 2:
        raise ValueError(
            f"gradient features must be [K,D], got {tuple(features.shape)}"
        )
    return (features @ features.T) / float(max(int(parameter_count), 1))


def parameter_gradient_gram(
    objectives: Sequence[torch.Tensor],
    parameters: Sequence[torch.Tensor],
    *,
    sketch_dim: int = 0,
    sketch_seed: int = 0,
) -> torch.Tensor:
    """Return the normalized (optionally sketched) complete-gradient Gram."""

    features, parameter_count = parameter_gradient_features(
        objectives,
        parameters,
        sketch_dim=int(sketch_dim),
        sketch_seed=int(sketch_seed),
    )
    return gram_from_gradient_features(features, parameter_count)


class _BackwardOnlyCurrentHorizonWeight(torch.autograd.Function):
    """Preserve a loss value while reading its coefficient at backward time.

    Calibration happens after the rollout graph is built but before the real
    backward.  A normal multiplication captures the previous coefficient in
    the graph.  This small custom node lets the same calibration batch use its
    newly solved batch-conditioned weight without a second forward pass.
    """

    @staticmethod
    def forward(ctx, loss: torch.Tensor, controller, horizon: int):
        ctx.controller = controller
        ctx.horizon = int(horizon)
        return loss.clone()

    @staticmethod
    def backward(ctx, grad_output: torch.Tensor):
        coefficient = ctx.controller.backward_weight(
            ctx.horizon, device=grad_output.device, dtype=grad_output.dtype
        )
        return grad_output * coefficient, None, None


class GlobalHorizonWienerController(nn.Module):
    """Online global Wiener estimator over complete horizon gradients."""

    def __init__(
        self,
        state_dim: int,
        *,
        max_horizon: int = 1024,
        ema: float = 0.95,
        residual_ema: float = 0.99,
        warmup_batches: int = 8,
        probe_every: int = 16,
        min_probes: int = 8,
        noise_model: str = "diagonal_gaussian",
        spatial_shape: Optional[Tuple[int, int, int]] = None,
        ridge: float = 1e-8,
        anchor: float = 0.0,
        local_fidelity: float = 0.0,
        solver_iterations: int = 256,
        sketch_dim: int = 8192,
        sketch_seed: int = 1729,
        noise_draws: int = 4,
        batch_conditioned: bool = True,
        superbatch_groups: int = 1,
        static_gain: float = -1.0,
        static_mode: str = "delayed_tied",
    ) -> None:
        super().__init__()
        self.max_horizon = int(max_horizon)
        self.ema = float(ema)
        self.min_probes = max(1, int(min_probes))
        self.ridge = max(0.0, float(ridge))
        self.anchor = max(0.0, float(anchor))
        self.local_fidelity = float(local_fidelity)
        if not 0.0 <= self.local_fidelity <= 1.0:
            raise ValueError("global Wiener local fidelity must lie in [0,1]")
        self.solver_iterations = max(1, int(solver_iterations))
        requested_sketch = max(0, int(sketch_dim))
        self.sketch_dim = (
            0
            if requested_sketch == 0
            else 1 << max(0, requested_sketch - 1).bit_length()
        )
        self.sketch_seed = int(sketch_seed)
        self.noise_draws = max(1, int(noise_draws))
        self.batch_conditioned = bool(batch_conditioned)
        self.superbatch_groups = int(superbatch_groups)
        if self.superbatch_groups < 1:
            raise ValueError("global Wiener superbatch groups must be positive")
        if self.superbatch_groups > 1 and not self.batch_conditioned:
            raise ValueError(
                "global Wiener superbatch grouping requires batch-conditioned mode"
            )
        self.static_gain = float(static_gain)
        self.static_mode = str(static_mode)
        self.fixed_static = self.static_gain >= 0.0
        if self.fixed_static and not 0.0 <= self.static_gain <= 1.0:
            raise ValueError("global Wiener static gain must lie in [0,1]")
        if self.static_mode not in {"delayed_tied", "exponential"}:
            raise ValueError(
                "global Wiener static mode must be 'delayed_tied' or 'exponential'"
            )
        if not 0.0 <= self.ema < 1.0:
            raise ValueError("global Wiener EMA must lie in [0,1)")

        # Reuse the mature, domain-specific innovation loaders and samplers.
        # depth=1 is sufficient because no internal route is ever constructed.
        self.innovation = DualWienerController(
            state_dim=int(state_dim),
            depth=1,
            max_horizon=self.max_horizon,
            ema=float(ema),
            residual_ema=float(residual_ema),
            warmup_batches=int(warmup_batches),
            probe_every=int(probe_every),
            min_probes=self.min_probes,
            noise_model=str(noise_model),
            spatial_shape=spatial_shape,
        )
        self.register_buffer("weights", torch.ones(self.max_horizon))
        if self.fixed_static:
            indices = torch.arange(self.max_horizon, dtype=self.weights.dtype)
            if self.static_mode == "delayed_tied":
                self.weights[1:].fill_(self.static_gain)
            else:
                self.weights.copy_(self.static_gain ** indices)
        self.register_buffer(
            "total_gram", torch.zeros(self.max_horizon, self.max_horizon)
        )
        self.register_buffer(
            "noise_gram", torch.zeros(self.max_horizon, self.max_horizon)
        )
        self.register_buffer("probe_updates", torch.zeros((), dtype=torch.long))
        self.register_buffer("solved_batches", torch.zeros((), dtype=torch.long))

        self._total_terms: DefaultDict[int, List[torch.Tensor]] = defaultdict(list)
        self._noise_terms: DefaultDict[int, List[torch.Tensor]] = defaultdict(list)
        self._superbatch_local_counts: Optional[torch.Tensor] = None
        self._pending_weights: Optional[torch.Tensor] = None
        self._active_horizon = 0
        self._last_total_trace = 0.0
        self._last_noise_trace = 0.0
        self._last_noise_fraction = 0.0
        self._last_projected_gradient = 0.0
        self._last_loewner_violation = 0.0
        self._last_noise_draws = 0
        self._last_superbatch_group_size = 0
        self._last_global_risk_over_open = 1.0
        self._last_local_risk_over_open = 1.0
        self._last_cross_risk = 0.0

    @property
    def collecting(self) -> bool:
        return bool(not self.fixed_static and self.innovation.collecting)

    def begin_batch(self) -> None:
        if not self.fixed_static:
            self.innovation.begin_batch()
        self._total_terms = defaultdict(list)
        self._noise_terms = defaultdict(list)
        self._superbatch_local_counts = None
        self._pending_weights = None
        self._active_horizon = 0

    def observe_and_sample(
        self,
        horizon: int,
        prediction: torch.Tensor,
        target: torch.Tensor,
    ) -> Optional[torch.Tensor]:
        """Update residual statistics and draw coherent innovation replicas.

        The replicas are folded into the leading batch dimension before calling
        the domain sampler.  Stateful AR/bootstrap samplers therefore preserve
        one coherent trajectory for every ``(draw, sample)`` pair across all
        horizons instead of accidentally resampling independent marginals.
        """

        if self.fixed_static:
            return None
        horizon = int(horizon)
        self.innovation.observe_residual(horizon, prediction - target)
        if not self.collecting:
            return None
        draws = self.noise_draws
        expanded = (
            prediction.detach()
            .unsqueeze(0)
            .expand(draws, *prediction.shape)
            .reshape(draws * prediction.shape[0], *prediction.shape[1:])
        )
        sampled = self.innovation.noise_covector(horizon, expanded)
        if sampled is None:
            return None
        return sampled.reshape(draws, *prediction.shape)

    def add_probe_terms(
        self,
        horizon: int,
        total: torch.Tensor,
        noise: Optional[Sequence[torch.Tensor]],
    ) -> None:
        horizon = int(horizon)
        if not self.collecting or noise is None:
            return
        if horizon < 0 or horizon >= self.max_horizon:
            raise ValueError(
                f"global Wiener horizon {horizon} is outside [0,{self.max_horizon})"
            )
        if self.superbatch_groups > 1:
            total = self._superbatch_group_sums(total, label="total")
        self._total_terms[horizon].append(total)
        if isinstance(noise, torch.Tensor):
            noise_values = [noise]
        else:
            noise_values = list(noise)
        if len(noise_values) != self.noise_draws:
            raise ValueError(
                f"expected {self.noise_draws} global Wiener noise draws, "
                f"got {len(noise_values)} at horizon {horizon}"
            )
        if self.superbatch_groups > 1:
            noise_values = [
                self._superbatch_group_sums(value, label="noise")
                for value in noise_values
            ]
        self._noise_terms[horizon].extend(noise_values)
        self._active_horizon = max(self._active_horizon, horizon + 1)

    def _superbatch_group_sums(
        self, per_sample: torch.Tensor, *, label: str
    ) -> torch.Tensor:
        """Split a per-sample probe objective into equal local group sums.

        Each DDP rank uses the same group index for the corresponding contiguous
        slice of its local batch.  Calibration later all-reduces these sums and
        divides by the rank-global group counts before forming any Gram.  Equal
        local group sizes make every global subgroup equally weighted and avoid
        silently changing the requested arithmetic mean over group Grams.
        """

        if per_sample.ndim != 1:
            raise ValueError(
                f"global Wiener superbatch {label} objective must be [B], got "
                f"{tuple(per_sample.shape)}"
            )
        batch = int(per_sample.shape[0])
        groups = self.superbatch_groups
        if batch < groups or batch % groups != 0:
            raise ValueError(
                "global Wiener superbatch calibration requires each rank-local "
                f"batch B to be divisible by M: B={batch}, M={groups}"
            )
        group_size = batch // groups
        counts = torch.full(
            (groups,),
            group_size,
            device=per_sample.device,
            dtype=torch.float64,
        )
        if self._superbatch_local_counts is None:
            self._superbatch_local_counts = counts
        elif not torch.equal(self._superbatch_local_counts, counts):
            raise RuntimeError(
                "global Wiener superbatch geometry changed within one rollout: "
                f"expected {self._superbatch_local_counts.tolist()}, got "
                f"{counts.tolist()}"
            )
        return per_sample.reshape(groups, group_size).sum(dim=1)

    def weight_loss(self, loss: torch.Tensor, horizon: int) -> torch.Tensor:
        """Keep ``loss``'s value and multiply only its backward derivative."""

        horizon = int(horizon)
        if horizon < 0 or horizon >= self.max_horizon:
            raise ValueError(
                f"global Wiener horizon {horizon} is outside [0,{self.max_horizon})"
            )
        if self.batch_conditioned:
            return _BackwardOnlyCurrentHorizonWeight.apply(loss, self, horizon)
        coefficient = self.weights[horizon].detach().clone().to(
            device=loss.device, dtype=loss.dtype
        )
        detached = loss.detach()
        return detached + coefficient * (loss - detached)

    def backward_weight(
        self, horizon: int, *, device: torch.device, dtype: torch.dtype
    ) -> torch.Tensor:
        """Return the coefficient selected for the imminent real backward."""

        horizon = int(horizon)
        source = (
            self._pending_weights
            if self.batch_conditioned and self._pending_weights is not None
            else self.weights
        )
        if horizon < 0 or horizon >= int(source.shape[0]):
            raise ValueError(
                f"global Wiener horizon {horizon} is outside [0,{source.shape[0]})"
            )
        return source[horizon].detach().to(device=device, dtype=dtype)

    def _objective_sets(
        self,
    ) -> Tuple[List[torch.Tensor], List[List[torch.Tensor]]]:
        if self._active_horizon <= 0:
            return [], []
        total: List[torch.Tensor] = []
        noise_by_horizon: List[List[torch.Tensor]] = []
        for horizon in range(self._active_horizon):
            total_terms = self._total_terms.get(horizon, [])
            noise_terms = self._noise_terms.get(horizon, [])
            if not total_terms or not noise_terms:
                return [], []
            if self.batch_conditioned and len(total_terms) != 1:
                raise RuntimeError(
                    "batch-conditioned global Wiener requires exactly one shared "
                    "rollout start per optimizer micro-batch; got "
                    f"{len(total_terms)} terms at horizon {horizon}"
                )
            expected_noise = self.noise_draws * len(total_terms)
            if len(noise_terms) != expected_noise:
                raise RuntimeError(
                    f"global Wiener horizon {horizon} has {len(noise_terms)} "
                    f"noise objectives; expected {expected_noise}"
                )
            total.append(torch.stack(total_terms).mean())
            noise_by_horizon.append(noise_terms)

        # In batch-conditioned mode there is one start, hence exactly M coherent
        # draw sets.  The legacy pooled mode retains the old ability to average
        # starts, but forms an independent Gram for every (start, draw) pair
        # instead of averaging noise objectives before squaring them.
        draw_sets: List[List[torch.Tensor]] = []
        for draw_index in range(len(noise_by_horizon[0])):
            draw_sets.append(
                [noise_by_horizon[h][draw_index] for h in range(self._active_horizon)]
            )
        return total, draw_sets

    def _superbatch_objective_sets(
        self,
    ) -> Tuple[List[List[torch.Tensor]], List[List[List[torch.Tensor]]]]:
        """Return group-major total and draw/group-major noise objectives.

        Shapes in nested-list notation are ``[M][K]`` for total and
        ``[draw][M][K]`` for noise.  Every scalar is a rank-local group SUM;
        :meth:`calibrate` converts it to the rank-global group mean before Gram.
        """

        if self._active_horizon <= 0:
            return [], []
        groups = self.superbatch_groups
        total_by_horizon: List[torch.Tensor] = []
        noise_by_horizon: List[List[torch.Tensor]] = []
        for horizon in range(self._active_horizon):
            total_terms = self._total_terms.get(horizon, [])
            noise_terms = self._noise_terms.get(horizon, [])
            if not total_terms or not noise_terms:
                return [], []
            if len(total_terms) != 1:
                raise RuntimeError(
                    "superbatch-conditioned global Wiener requires exactly one "
                    f"shared rollout start; got {len(total_terms)} terms at "
                    f"horizon {horizon}"
                )
            total_value = total_terms[0]
            if total_value.ndim != 1 or int(total_value.shape[0]) != groups:
                raise RuntimeError(
                    f"superbatch total at horizon {horizon} must be [{groups}], "
                    f"got {tuple(total_value.shape)}"
                )
            if len(noise_terms) != self.noise_draws:
                raise RuntimeError(
                    f"superbatch horizon {horizon} has {len(noise_terms)} noise "
                    f"draws; expected {self.noise_draws}"
                )
            for value in noise_terms:
                if value.ndim != 1 or int(value.shape[0]) != groups:
                    raise RuntimeError(
                        f"superbatch noise at horizon {horizon} must be "
                        f"[{groups}], got {tuple(value.shape)}"
                    )
            total_by_horizon.append(total_value)
            noise_by_horizon.append(noise_terms)

        total_sets = [
            [total_by_horizon[horizon][group] for horizon in range(self._active_horizon)]
            for group in range(groups)
        ]
        noise_sets = [
            [
                [
                    noise_by_horizon[horizon][draw][group]
                    for horizon in range(self._active_horizon)
                ]
                for group in range(groups)
            ]
            for draw in range(self.noise_draws)
        ]
        return total_sets, noise_sets

    @torch.no_grad()
    def _update_running_grams(
        self, total_value: torch.Tensor, noise_value: torch.Tensor
    ) -> None:
        horizon = int(total_value.shape[0])
        previous_count = int(self.probe_updates.detach().cpu())
        total_old = self.total_gram[:horizon, :horizon]
        noise_old = self.noise_gram[:horizon, :horizon]
        if previous_count == 0:
            total_next = total_value
            noise_next = noise_value
        elif previous_count < self.min_probes:
            denominator = float(previous_count + 1)
            total_next = (total_old * previous_count + total_value) / denominator
            noise_next = (noise_old * previous_count + noise_value) / denominator
        else:
            total_next = total_old * self.ema + total_value * (1.0 - self.ema)
            noise_next = noise_old * self.ema + noise_value * (1.0 - self.ema)
        total_old.copy_(0.5 * (total_next + total_next.T))
        noise_old.copy_(0.5 * (noise_next + noise_next.T))
        self.probe_updates.add_(1)

    def calibrate(self, parameters: Iterable[torch.Tensor]) -> bool:
        """Estimate global Grams and stage weights for the current backward."""

        if not self.collecting:
            return False
        if self.superbatch_groups > 1:
            total_group_sets, noise_draw_group_sets = (
                self._superbatch_objective_sets()
            )
            if not total_group_sets:
                return False
            horizon = len(total_group_sets[0])
        else:
            total_objectives, noise_objective_sets = self._objective_sets()
            if not total_objectives:
                return False
            horizon = len(total_objectives)
        trainable = [parameter for parameter in parameters if parameter.requires_grad]
        if not trainable:
            return False

        # Rotate the CountSketch between probe batches, but use the identical
        # projection for T and R within a batch.  EMA/arithmetic pooling then
        # averages away collision noise while preserving a matched subtraction.
        probe_seed = self.sketch_seed + int(self.probe_updates.detach().cpu()) * 1009
        if self.superbatch_groups > 1:
            total_group_features = []
            parameter_count: Optional[int] = None
            for group_objectives in total_group_sets:
                features, group_parameter_count = parameter_gradient_features(
                    group_objectives,
                    trainable,
                    sketch_dim=self.sketch_dim,
                    sketch_seed=probe_seed,
                )
                if parameter_count is None:
                    parameter_count = group_parameter_count
                elif group_parameter_count != parameter_count:
                    raise RuntimeError(
                        "parameter count changed across superbatch total groups"
                    )
                total_group_features.append(features)
            total_feature_tensor = torch.stack(total_group_features)

            noise_draw_features = []
            for draw_group_sets in noise_draw_group_sets:
                draw_features = []
                for group_objectives in draw_group_sets:
                    features, noise_parameter_count = parameter_gradient_features(
                        group_objectives,
                        trainable,
                        sketch_dim=self.sketch_dim,
                        sketch_seed=probe_seed,
                    )
                    if noise_parameter_count != parameter_count:
                        raise RuntimeError(
                            "total and noise probes used different trainable "
                            "parameter counts"
                        )
                    draw_features.append(features)
                noise_draw_features.append(torch.stack(draw_features))
            noise_feature_tensor = torch.stack(noise_draw_features)
            if self._superbatch_local_counts is None:
                raise RuntimeError("missing global Wiener superbatch group counts")
            group_counts = self._superbatch_local_counts.detach().clone()

            if (
                dist.is_available()
                and dist.is_initialized()
                and dist.get_world_size() > 1
            ):
                # Every group is the union of the same local slice on all ranks.
                # Check the strict equal-size contract, then reduce SUM features
                # and counts before division.  No rank-local Gram is averaged.
                count_min = group_counts.clone()
                count_max = group_counts.clone()
                dist.all_reduce(count_min, op=dist.ReduceOp.MIN)
                dist.all_reduce(count_max, op=dist.ReduceOp.MAX)
                if not torch.equal(count_min, count_max):
                    raise RuntimeError(
                        "global Wiener superbatch group sizes differ across DDP "
                        f"ranks: min={count_min.tolist()}, max={count_max.tolist()}"
                    )
                dist.all_reduce(total_feature_tensor, op=dist.ReduceOp.SUM)
                dist.all_reduce(noise_feature_tensor, op=dist.ReduceOp.SUM)
                dist.all_reduce(group_counts, op=dist.ReduceOp.SUM)

            total_feature_tensor.div_(group_counts[:, None, None])
            noise_feature_tensor.div_(group_counts[None, :, None, None])
            parameter_count = int(parameter_count or 0)
            total_value = torch.stack(
                [
                    gram_from_gradient_features(features, parameter_count)
                    for features in total_feature_tensor
                ]
            ).mean(dim=0)
            noise_value = torch.stack(
                [
                    gram_from_gradient_features(features, parameter_count)
                    for draw_features in noise_feature_tensor
                    for features in draw_features
                ]
            ).mean(dim=0)
            noise_draw_count = int(noise_feature_tensor.shape[0])
            self._last_superbatch_group_size = int(group_counts[0].item())
        else:
            # Preserve the original M=1 implementation exactly: each row is the
            # complete local-batch mean objective, DDP averages its feature, and
            # only then is the complete optimizer-batch Gram formed.
            total_features, parameter_count = parameter_gradient_features(
                total_objectives,
                trainable,
                sketch_dim=self.sketch_dim,
                sketch_seed=probe_seed,
            )
            noise_features = []
            for noise_objectives in noise_objective_sets:
                features, noise_parameter_count = parameter_gradient_features(
                    noise_objectives,
                    trainable,
                    sketch_dim=self.sketch_dim,
                    sketch_seed=probe_seed,
                )
                if noise_parameter_count != parameter_count:
                    raise RuntimeError(
                        "total and noise probes used different trainable parameter counts"
                    )
                noise_features.append(features)
            noise_feature_tensor = torch.stack(noise_features)
            if (
                dist.is_available()
                and dist.is_initialized()
                and dist.get_world_size() > 1
            ):
                # DDP applies the rank-mean gradient.  Reduce the features first
                # and only then form their Gram; averaging local Grams estimates
                # a different objective and omits cross-rank signal terms.
                dist.all_reduce(total_features, op=dist.ReduceOp.SUM)
                dist.all_reduce(noise_feature_tensor, op=dist.ReduceOp.SUM)
                world = float(dist.get_world_size())
                total_features.div_(world)
                noise_feature_tensor.div_(world)

            total_value = gram_from_gradient_features(
                total_features, parameter_count
            )
            noise_value = torch.stack(
                [
                    gram_from_gradient_features(features, parameter_count)
                    for features in noise_feature_tensor
                ]
            ).mean(dim=0)
            noise_draw_count = int(noise_feature_tensor.shape[0])
            self._last_superbatch_group_size = 0

        self._update_running_grams(total_value, noise_value)
        total_running = self.total_gram[:horizon, :horizon]
        noise_running = self.noise_gram[:horizon, :horizon]
        with torch.no_grad():
            self._last_total_trace = float(total_running.diagonal().sum().cpu())
            self._last_noise_trace = float(noise_running.diagonal().sum().cpu())
            self._last_noise_fraction = self._last_noise_trace / max(
                self._last_total_trace, 1e-30
            )
            self._last_noise_draws = noise_draw_count
            if int(self.probe_updates.detach().cpu()) >= self.min_probes:
                solve_total = total_value if self.batch_conditioned else total_running
                solve_noise = noise_value if self.batch_conditioned else noise_running
                solve_total, solve_noise, signal, violation = project_noise_below_total(
                    solve_total, solve_noise, floor=self.ridge
                )
                risk_total = solve_total
                risk_signal = signal
                mixed_total, mixed_signal = mix_global_local_wiener_moments(
                    solve_total,
                    signal,
                    self.local_fidelity,
                )
                candidate, residual = solve_box_wiener(
                    mixed_total,
                    mixed_signal,
                    initial=self.weights[:horizon],
                    ridge=self.ridge,
                    anchor=self.anchor,
                    iterations=self.solver_iterations,
                )
                # Report both estimands using the un-mixed projected moments.
                # Constants are included, so these are actual conditional MSE
                # estimates rather than only quadratic objectives.
                weights64 = candidate.detach().double()
                total64 = risk_total.detach().double()
                noise64 = solve_noise.detach().double()
                original_signal64 = risk_signal.detach().double()
                ones64 = torch.ones_like(weights64)
                global_risk = (
                    weights64 @ total64 @ weights64
                    - 2.0 * weights64 @ original_signal64 @ ones64
                    + ones64 @ original_signal64 @ ones64
                ).clamp_min(0.0)
                local_risk = (
                    weights64.square() * total64.diagonal()
                    - 2.0 * weights64 * original_signal64.diagonal()
                    + original_signal64.diagonal()
                ).sum().clamp_min(0.0)
                open_global_risk = (ones64 @ noise64 @ ones64).clamp_min(1e-30)
                open_local_risk = noise64.diagonal().sum().clamp_min(1e-30)
                self._last_global_risk_over_open = float(
                    (global_risk / open_global_risk).cpu()
                )
                self._last_local_risk_over_open = float(
                    (local_risk / open_local_risk).cpu()
                )
                self._last_cross_risk = float((global_risk - local_risk).cpu())
                self._pending_weights = candidate.detach()
                self._last_projected_gradient = residual
                self._last_loewner_violation = violation
        return self._pending_weights is not None

    def end_batch(self) -> None:
        if self._pending_weights is not None:
            horizon = int(self._pending_weights.shape[0])
            with torch.no_grad():
                self.weights[:horizon].copy_(self._pending_weights.clamp(0.0, 1.0))
                self.solved_batches.add_(1)
        if not self.fixed_static:
            self.innovation.end_batch()
        self._total_terms = defaultdict(list)
        self._noise_terms = defaultdict(list)
        self._superbatch_local_counts = None
        self._pending_weights = None

    def diagnostics(self, horizon: int) -> Dict[str, float]:
        horizon = max(1, min(int(horizon), self.max_horizon))
        values = self.weights[:horizon].detach().float()
        return {
            "ar/global_wiener_weight_mean": float(values.mean().cpu()),
            "ar/global_wiener_weight_min": float(values.min().cpu()),
            "ar/global_wiener_weight_max": float(values.max().cpu()),
            "ar/global_wiener_noise_fraction": float(self._last_noise_fraction),
            "ar/global_wiener_total_trace": float(self._last_total_trace),
            "ar/global_wiener_noise_trace": float(self._last_noise_trace),
            "ar/global_wiener_probe_updates": float(self.probe_updates.detach().cpu()),
            "ar/global_wiener_solved_batches": float(self.solved_batches.detach().cpu()),
            "ar/global_wiener_projected_gradient": float(
                self._last_projected_gradient
            ),
            "ar/global_wiener_collecting": float(self.collecting),
            "ar/global_wiener_noise_draws": float(self._last_noise_draws),
            "ar/global_wiener_batch_conditioned": float(self.batch_conditioned),
            "ar/global_wiener_superbatch_groups": float(self.superbatch_groups),
            "ar/global_wiener_superbatch_group_size": float(
                self._last_superbatch_group_size
            ),
            "ar/global_wiener_anchor": float(self.anchor),
            "ar/global_wiener_local_fidelity": float(self.local_fidelity),
            "ar/global_wiener_global_risk_over_open": float(
                self._last_global_risk_over_open
            ),
            "ar/global_wiener_local_risk_over_open": float(
                self._last_local_risk_over_open
            ),
            "ar/global_wiener_cross_risk": float(self._last_cross_risk),
            "ar/global_wiener_fixed_static": float(self.fixed_static),
            "ar/global_wiener_static_gain": float(
                self.static_gain if self.fixed_static else -1.0
            ),
            "ar/global_wiener_feature_then_gram": 1.0,
            "ar/global_wiener_loewner_violation": float(
                self._last_loewner_violation
            ),
        }

    @torch.no_grad()
    def export_state(self, horizon: int) -> Dict[str, object]:
        horizon = max(1, min(int(horizon), self.max_horizon))
        return {
            "format_version": 4,
            "estimator": "global_horizon_wiener",
            "objective": (
                "subgroup_pooled_parameter_gradient_mse"
                if self.superbatch_groups > 1
                else (
                    "complete_parameter_gradient_mse"
                    if self.local_fidelity == 0.0
                    else "global_local_horizon_gradient_mse"
                )
            ),
            "horizon": horizon,
            "weights": self.weights[:horizon].detach().float().cpu().tolist(),
            "total_gram": self.total_gram[:horizon, :horizon]
            .detach()
            .float()
            .cpu()
            .tolist(),
            "noise_gram": self.noise_gram[:horizon, :horizon]
            .detach()
            .float()
            .cpu()
            .tolist(),
            "probe_updates": int(self.probe_updates.detach().cpu()),
            "solved_batches": int(self.solved_batches.detach().cpu()),
            "noise_fraction": float(self._last_noise_fraction),
            "projected_gradient": float(self._last_projected_gradient),
            "parameter_gradient_geometry": (
                "exact" if self.sketch_dim == 0 else "countsketch"
            ),
            "parameter_gradient_sketch_dim": int(self.sketch_dim),
            "parameter_gradient_sketch_seed": int(self.sketch_seed),
            "noise_draws_per_batch": int(self.noise_draws),
            "batch_conditioned": bool(self.batch_conditioned),
            "superbatch_groups": int(self.superbatch_groups),
            "superbatch_group_size": int(self._last_superbatch_group_size),
            "moment_geometry": (
                "mean_of_disjoint_subgroup_mean_gradient_grams"
                if self.superbatch_groups > 1
                else "complete_optimizer_batch_mean_gradient_gram"
            ),
            "real_backward_geometry": "complete_optimizer_batch_mean_loss",
            "fixed_static": bool(self.fixed_static),
            "static_gain": float(self.static_gain),
            "static_mode": self.static_mode,
            "fully_open_anchor": float(self.anchor),
            "local_fidelity": float(self.local_fidelity),
            "global_risk_over_open": float(self._last_global_risk_over_open),
            "local_risk_over_open": float(self._last_local_risk_over_open),
            "cross_risk": float(self._last_cross_risk),
            "distributed_moment_order": "all_reduce_feature_then_gram",
            "loewner_violation_before_projection": float(
                self._last_loewner_violation
            ),
            "innovation": self.innovation.export_state(horizon),
        }
