"""Field Koopman autoencoder with hard coordinate-corrector dynamics.

This is the clean controlled model for testing the hard corrector idea outside
of the Mamba harness.  It uses the same normal convolutional Koopman AE as
koopman_field_gramian, but replaces the latent transition

    z_{t+1} = A z_t + f(u_t)

by the full coordinate-corrected transition

    z_t = (I + Q_t) y_t
    y_{t+1} = A y_t + f(u_t)
    z_{t+1} = (I + Q_{t+1}) y_{t+1}

where Q_t is a bounded diagonal corrector generated by one shared operator.
For channelized latents, A is the same channelized Koopman matrix used by the
base model and Q is elementwise [B, C, D].
"""

from __future__ import annotations

from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .koopman_field_gram import KoopmanFieldGramianModel


class KoopmanFieldHardCorrectorModel(KoopmanFieldGramianModel):
    """Clean Koopman AE with hard coordinate-corrected latent transition.

    The encoder/decoder/stimulus force are inherited from
    KoopmanFieldGramianModel.  Only transition_latent is replaced.

    Notes
    -----
    * Q is diagonal/elementwise.  This keeps the model cheap and avoids a dense
      inverse in high-dimensional latent space.
    * The corrector operator is shared for t and t+1.  Q_t is predicted from
      the current latent/context.  Q_{t+1} is predicted from the macro next
      latent y_{t+1} and the same stimulus context.  This is a practical
      one-step approximation of a shared local corrector field.
    * The input force is inside the corrected coordinate, i.e. z_{t+1} =
      (1+Q_{t+1}) * (A ((1+Q_t)^{-1} z_t) + f_t).  This prevents the input
      path from bypassing the coordinate correction.
    """

    def __init__(
        self,
        *args,
        corrector_rho: float = 0.1,
        corrector_hidden_mult: int = 2,
        corrector_init_std: float = 1e-2,
        corrector_use_stim: bool = True,
        corrector_detach_next_context: bool = False,
        corrector_min_denominator: float = 1e-4,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.corrector_rho = float(corrector_rho)
        self.corrector_hidden_mult = int(corrector_hidden_mult)
        self.corrector_init_std = float(corrector_init_std)
        self.corrector_use_stim = bool(corrector_use_stim)
        self.corrector_detach_next_context = bool(corrector_detach_next_context)
        self.corrector_min_denominator = float(corrector_min_denominator)

        ctx_dim = self.latent_dim
        if self.corrector_use_stim:
            ctx_dim += self.hidden_dim
        hidden = max(self.latent_dim, int(self.corrector_hidden_mult) * self.latent_dim)
        hidden = min(hidden, 4096)
        self.corrector_head = nn.Sequential(
            nn.Linear(ctx_dim, hidden),
            nn.GELU(),
            nn.Linear(hidden, self.latent_dim),
        )
        self._init_corrector_head()

    def _init_corrector_head(self) -> None:
        # Nonzero init is important.  A zero head makes Q_t=Q_{t+1}=0 exactly,
        # so the hard branch starts as pure fixed-A and tends to be starved.
        for module in self.corrector_head.modules():
            if isinstance(module, nn.Linear):
                nn.init.normal_(module.weight, mean=0.0, std=self.corrector_init_std)
                nn.init.zeros_(module.bias)

    def _corrector_context(self, z_like: torch.Tensor, stim_window: torch.Tensor) -> torch.Tensor:
        z_flat = self._to_flat(z_like)
        if not self.corrector_use_stim:
            return z_flat
        stim_feat = self.encode_stim(stim_window)
        return torch.cat([z_flat, stim_feat], dim=-1)

    def corrector(self, z_like: torch.Tensor, stim_window: torch.Tensor) -> torch.Tensor:
        q = self.corrector_head(self._corrector_context(z_like, stim_window))
        q = self.corrector_rho * torch.tanh(q)
        if self.channelized_koopman:
            q = q.reshape(q.shape[0], self.latent_channels, self.latent_channel_dim)
        return q

    def _safe_denominator(self, q: torch.Tensor) -> torch.Tensor:
        denom = 1.0 + q
        eps = self.corrector_min_denominator
        if eps <= 0:
            return denom
        # Since |q| < rho and rho should be < 1, this is normally inactive.
        # It is just a guard against accidental bad hyperparameters.
        return torch.where(denom.abs() < eps, denom.sign().clamp(min=0).mul(2).sub(1) * eps, denom)

    def _apply_A(self, z: torch.Tensor, A: torch.Tensor) -> torch.Tensor:
        if self.channelized_koopman:
            zc = self._to_channel(z)
            if A.dim() == 3:
                return torch.einsum("bci,coi->bco", zc, A)
            return F.linear(zc, A, None)
        return F.linear(z, A, None)

    def transition_latent(self, z_t: torch.Tensor, stim_window: torch.Tensor) -> torch.Tensor:
        A = self.effective_A()
        force = self.stimulus_force(stim_window)

        q_t = self.corrector(z_t, stim_window)
        y_t = self._to_channel(z_t) if self.channelized_koopman else z_t
        y_t = y_t / self._safe_denominator(q_t)

        y_next = self._apply_A(y_t, A) + force
        next_context = y_next.detach() if self.corrector_detach_next_context else y_next
        q_next = self.corrector(next_context, stim_window)
        z_next = (1.0 + q_next) * y_next
        return z_next

    def forward(self, stim_window: torch.Tensor, state_window: torch.Tensor, step_idx=None, return_aux: bool = False):
        z_t = self.encode_state(state_window)
        z_next = self.transition_latent(z_t, stim_window)
        pred_frame = self.decode_state(z_next)
        pred = pred_frame.unsqueeze(1)
        if not return_aux:
            return pred

        recon = self.decode_state(z_t).unsqueeze(1)
        A = self.effective_A()
        with torch.no_grad():
            q_t = self.corrector(z_t, stim_window)
            force = self.stimulus_force(stim_window)
            y_t = (self._to_channel(z_t) if self.channelized_koopman else z_t) / self._safe_denominator(q_t)
            y_next = self._apply_A(y_t, A) + force
            q_next = self.corrector(y_next, stim_window)
            # Effective diagonal relative perturbation around the macro A in the
            # diagonal-corrector sense.  For full A this is still the coordinate
            # scaling ratio; it is the right scalar diagnostic for Q activity.
            denom = self._safe_denominator(q_t)
            scale_ratio = (1.0 + q_next) / denom
            delta_rel = (scale_ratio - 1.0).abs().mean()
            q_abs = q_t.abs().mean()
            q_next_abs = q_next.abs().mean()
            q_diff_abs = (q_next - q_t).abs().mean()

        return pred, {
            "z": z_t,
            "z_next": z_next,
            "recon": recon,
            "A_sigma": torch.linalg.matrix_norm(A.detach(), ord=2).mean(),
            "force_scale": torch.exp(self.log_force_scale.detach()),
            "koopman_encoder": 1.0,
            "koopman_channelized": float(self.channelized_koopman),
            "koopman_channels": float(self.latent_channels),
            "koopman_channel_dim": float(self.latent_channel_dim),
            "field_channels": float(self.field_channels),
            "corrector_abs": q_abs,
            "corrector_next_abs": q_next_abs,
            "corrector_diff_abs": q_diff_abs,
            "corrector_delta_rel": delta_rel,
            "corrector_rho": torch.tensor(self.corrector_rho, device=z_next.device, dtype=z_next.dtype),
        }
